FROM node:22-alpine
WORKDIR /app

# Копируем dist и package.json
COPY dist/apps/api ./dist
COPY package.json package-lock.json ./

# Устанавливаем зависимости (без dev)
RUN npm ci --omit=dev

CMD ["node", "dist/main.js"]
