version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  lifestyle-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: lifestyle-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '${API_PORT}:3000'

  lifestyle-front:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: lifestyle-front
    depends_on:
      - lifestyle-api
    ports:
      - '${FRONT_PORT}:80'

volumes:
  postgres-data:
