FROM arm64v8/node:22-alpine
WORKDIR /app

COPY dist/apps/api ./dist

COPY apps/api/prisma ./prisma

COPY package.json package-lock.json ./

RUN npm ci --omit=dev

RUN npx prisma generate

CMD ["node", "dist/main.js"]
