name: lifestyle-dashboard
region: ams
features:
  - buildpack-stack=ubuntu-22

services:
  - name: api
    dockerfile_path: Dockerfile.api
    http_port: 3000
    health_check:
      http_path: /api
    instance_count: 1
    instance_size_slug: basic-xxs
    github:
      repo: evtrnist/lifestyle-dashboard
      branch: main
      deploy_on_push: true
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

  - name: front
    dockerfile_path: Dockerfile.front
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    github:
      repo: evtrnist/lifestyle-dashboard
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    envs:
      - key: API_URL
        scope: RUN_TIME
        value: "http://api:3000"
