name: Build and Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build NX Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: npx nx build api --configuration=production

      - name: Build Frontend
        run: npx nx build front --configuration=production

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/

  docker:
    name: Build and Push Docker Images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dist from previous job
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Connect to Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-ci-runner --timeout=30s
          tailscale status

      - name: Allow insecure registry
        run: |
          echo '{ "insecure-registries": ["${{ secrets.REGISTRY_URL }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Raspberry Pi Registry
        run: |
          echo "${{ secrets.CR_PASSWORD }}" | docker login http://${{ secrets.REGISTRY_URL }} -u ${{ secrets.CR_USER }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build and push backend (NestJS)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/lifestyle-api:latest
          platforms: linux/arm64
          outputs: type=registry,insecure=true

      - name: Build and push frontend (Angular)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.front
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/lifestyle-front:latest
          platforms: linux/arm64
          outputs: type=registry,insecure=true
